language: python
env:
  global:
  - PYTHON=python
  - PIP=pip
  - SETUPTOOLS_SCM_PRETEND_VERSION=$TRAVIS_TAG
  - MAKE=make  
  - TWINE_USERNAME=davide.romanini
  # TWINE_PASSOWRD
  - secure: ANOvmeQluy3ZA7Ds08oJe11Ge2bSAIbepZyG0UbTscBh5YWhl7a5XTlL5obPXsNfJCo7nNpz/wQshpMNHhuNiKgJ9r2Pgyd7n7/iuoFWBLCVW5gP8811ThhHrP5sb3ayujWjYHIodV+QpnHFmgSoJKNs81qox7oczJ/KOksUOHx9u1FLPGCHqoANBpQA2ItxIhAQJFSLpVpIQIASl6zSlr0wXTkD9I60TJhRFykmlfxw4zvsc4Y7I3a/xgCHD7Z6T+9nPzdYf1+x9LbuNOxpJGnH632gIzkOoJsW26Q+rsGJamYjt0Q8y1Z+CzESDE37VDYPM84ZjdO7vtmeMdV/QTOHnXXsoh9WaycKM2sF4jQGmjeiahEArz7yQ5uu0QR6EAa1s2tzG7UG1oBCwbjwn+AniL+G6QpKwvOGfZXC8SCffRB3k24J1X6CexDWMbuZ3WKeOb4Rj1Z4paF2NN1xYj/wxBG9N93xxlLPZRPaCLRAJZBz3AMf13D9+8ytifaEFNSmGnGFCgRukGHHTv7ggVPyWsFnIGcP608tsY16mFo8uxT3CN3lEiMUS9rqJ4MxTN5LVr2J+3X4/o2b1sD9VyTBQz8T9PG0Rf1fJP8DUKT+C09Q4ERathT1cOQiZm1fZVwYOVIIYOSbE2FpC5xojq1vvaAoS1DURhDyrCGews4=
matrix:
  include:
  - os: linux
    sudo: required
    python: "3.8"
    services:
    - docker
    env:
    - DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 PLAT=manylinux1_x86_64
  - os: linux
    sudo: required
    python: "3.8"
    services:
    - docker
    env:
    - DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32 PLAT=manylinux1_i686
  - os: linux
    sudo: required
    python: "3.8"
    services:
    - docker
    env:
    - DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64 PLAT=manylinux2010_x86_64
  - os: osx
    language: generic
    osx_image: xcode8.3
    env: PYTHON=python3 PIP=pip3 HOMEBREW_NO_AUTO_UPDATE=1    
  - os: windows
    language: bash
    env: PYTHON_VERSION=3.7.8 PATH=/C/Python37:/C/Python37/Scripts:$PATH
  - os: windows
    language: bash
    env: PYTHON_VERSION=3.8.10 PIP="pip --use-feature=in-tree-build" PATH=/C/Python38:/C/Python38/Scripts:$PATH
  - os: windows
    language: bash
    env: PYTHON_VERSION=3.9.6 PIP="pip --use-feature=in-tree-build" PATH=/C/Python39:/C/Python39/Scripts:$PATH
before_install:
- if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install -y python --version=$PYTHON_VERSION && $PIP install cffi; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install python3 ; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then docker pull $DOCKER_IMAGE ; fi

script:
- "./build.sh buildci $TRAVIS_OS_NAME" 
- "./build.sh testci $TRAVIS_OS_NAME"
- if [ -n "$TRAVIS_TAG" ]; then ./build.sh publish ; fi
branches:
  only:
  - develop
  - "/^v\\d.*/"
